Repository rdkcentral/rdk-halif-test-hdmi_cec, pull requests merged in 2024-07, with the labels that each got.

#29 Feature/issues9: Support emulating a cec network
  Makefile
  profiles/stb-source-device.yaml
  profiles/tv_panel_5_devices.yaml
  profiles/vcomponent_hdmicec_profile_template.yaml
  src/main.c
  src/test_vcomponent.c
  vcomponent/include/vcomponent_hdmi_cec.h
  vcomponent/src/vchdmicec_device.c
  vcomponent/src/vchdmicec_device.h
  vcomponent/src/vcomponent_hdmi_cec.c
Labels: enhancement

#37 Feature/issue18 control plane integration
  Makefile
  assets/control_messages/activesource.yaml
  assets/control_messages/imageviewon.yaml
  assets/control_messages/inactivesource.yaml
  assets/control_messages/setosdname.yaml
  assets/control_messages/textviewon.yaml
  assets/validation_profiles/tv_panel_5_devices_validation.yaml
  docs/pages/hdmi_cec_emulator_design.md
  docs/pages/hdmi_cec_virtual_component_design.md
  src/main.c
  src/test_l3_hdmi_cec_driver.c
  src/test_vcomponent.c
  vcomponent/include/vcHdmiCec.h
  vcomponent/src/vcCommand.c
  vcomponent/src/vcCommand.h
  vcomponent/src/vcDevice.c
  vcomponent/src/vcDevice.h
  vcomponent/src/vcHdmiCec.c
  vcomponent/src/vchdmicec_device.h
  vcomponent/src/vcomponent_hdmi_cec.c
Labels: enhancement

#40 Document the control plane commands that will be supported
  docs/pages/hdmi_cec_VirtualComponent_ControlPlaneCommands.md
Labels: documentation

#38 Update L1 suite with specification 1.3.9
  skeletons/src/hdmi_cec_driver.c
  src/test_l1_hdmi_cec_driver.c
Labels: L1 related issues
