Repository rdkcentral/rdk-halif-test-hdmi_cec, pull requests merged in 2024-06, with the labels that each got.

#12 hdmi_cec: Test Profile: Adding MACRO ENABLE_ENHANCED_ERROR_CODE to enalbe/disable the enhanced error code tests
  profiles/hdmiCECExtendedEnumsNotSupported.yaml
  src/test_l1_hdmi_cec_driver.c
Labels: bug

#21 Feature/issues15 emulator startup
  Makefile
  docs/pages/hdmi_cec_emulator_design.md
  src/main.c
  src/test_vcomponent.c
  vcomponent/include/vcomponent_hdmi_cec.h
  vcomponent/profiles/profile_template.yaml
  vcomponent/profiles/test_sink.yaml
  vcomponent/profiles/test_source_skyxione.yaml
  vcomponent/src/vcomponent_hdmi_cec.c
Labels: enhancement

#28 Feature/gh24 hdmicec source l2 tests
  Makefile
  build.sh
  docs/pages/hdmi-cec-sink_High-Level_TestSpec.md
  docs/pages/hdmi-cec-sink_L2_Low-Level_TestSpec.md
  docs/pages/hdmi-cec-source_High-Level_TestSpec.md
  docs/pages/hdmi-cec-source_L2_Low-Level_TestSpec.md
  docs/pages/l2_module_test_specification_template.md
  profiles/sink/sink_hdmiCEC.yml
  profiles/source/source_hdmiCEC.yml
  src/main.c
  src/test_l2_hdmi_cec_driver.c
  src/test_l2_hdmi_cec_sink_driver.c
  src/test_l2_hdmi_cec_source_driver.c
  src/test_register.c
  src/test_vcomponent.c
Labels: documentation
